apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmark-site-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookmark-site
  template:
    metadata:
      labels:
        app: bookmark-site
    spec:
      containers:
      - name: bookmark-site
        image: connorlakatos12/bookmark-site
        ports:
        - containerPort: 80
